require("jackdaw.options")
require("jackdaw.lazy")
require("jackdaw.keymap")
require("jackdaw.diagnostics")
require("jackdaw.commands")
require("jackdaw.test")

vim.cmd.colorscheme("catppuccin")
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none", ctermbg = "none" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none", ctermbg = "none" })
vim.api.nvim_set_hl(0, "FloatTitle", { bg = "none", ctermbg = "none" })
