vim.keymap.set("n", " ", "<Nop>", { silent = true, remap = false })
vim.keymap.set("n", "<leader>e", vim.cmd.Ex)
vim.keymap.set("x", "<leader>/", ":Commentary<cr>", { remap = false })
vim.keymap.set("v", "<leader>/", ":Commentary<cr>", { remap = false })
vim.keymap.set("n", "<leader>/", ":Commentary<cr>", { remap = false })
