vim.keymap.set("n", " ", "<Nop>", { silent = true })
vim.keymap.set("n", "<leader>e", vim.cmd.Ex)
vim.keymap.set("x", "<leader>/", ":Commentary<cr>")
vim.keymap.set("v", "<leader>/", ":Commentary<cr>")
vim.keymap.set("n", "<leader>/", ":Commentary<cr>")
vim.keymap.set("v", ">", ">gv2l")
vim.keymap.set("v", "<", "<gv2h")
